name: Test CI

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/Terminal.Calculator
    - name: Build
      run: dotnet build ./src/Terminal.Calculator --no-restore
    - name: Test
      run: dotnet test ./tests/Terminal.Calculator.UnitTests --no-build --verbosity normal
